In [2]:
import pandas as pd

In [3]:
shopping_data = pd.read_csv("data/processed/shopping_cleaned.csv")

In [4]:
shopping_data.head(5)

,Age,Gender,Item Purchased,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Shipping Type,Promo Code Used,Previous Purchases,Payment Method
0,31.0,Male,Leggings,24.231704,Nevada,M,Terra cotta,Winter,Present,Standard,No,0,Credit Card
1,38.0,Male,Sunglasses,36.545487,Oregon,S,Aubergine,Summer,Missing,Standard,No,0,Credit Card
2,26.0,Male,Leggings,23.595139,Nevada,XL,Brown,Winter,Missing,Standard,No,3,Credit Card
3,43.0,Male,Dress,34.079015,California,M,Terra cotta,Fall,Present,Standard,No,0,Credit Card
4,29.0,Male,Shorts,23.796439,Minnesota,M,Lavender,Summer,Present,Express,No,0,Credit Card

In [5]:
shopping_data['Season'].unique()

<StringArray>
['Winter', 'Summer', 'Fall', 'Spring']
Length: 4, dtype: str

In [9]:
shopping_data.pivot_table(values= 'Purchase Amount (USD)', index='Gender', columns = 'Season', aggfunc='mean')

Season           Fall     Spring     Summer     Winter
Gender
Female      38.636415  39.893283  38.975288  38.974280
Male        39.198257  38.996916  38.602033  37.923404
Non-binary  38.434052  42.210768  33.377797  40.149328

In [11]:
shopping_data.pivot_table(values= 'Purchase Amount (USD)', index='Color', columns = 'Season', aggfunc='sum')

Season                       Fall       Spring       Summer       Winter
Color
Aubergine             3187.347119    78.163902   502.025321  4265.951461
Baby blue              540.954615  2782.680597  3050.941003   915.377891
Black                 3202.572367   184.047533   324.547160  4758.458501
Brick red             3501.664330   221.816461   487.263950  4298.152282
Brown                 3811.398009   219.926643   107.017216  3287.473552
Burnt orange          3723.405332   180.018348   230.744058  4230.399982
Fuchsia                148.637986  1716.762832  2930.078969   734.033380
Lavender               532.127292  2134.416825  3909.914306   219.444132
Lemon yellow           339.755195  1858.529786  3894.506774   474.930158
Mauve                 3357.290264   184.539169   275.693562  3578.869980
Muted mustard yellow  3019.889365   339.652796   489.693112  3290.808618
Pale peach             392.004065  2005.687372  3294.084518   606.773268
Periwinkle             356.172835  2388.302138  3194.608079   325.224775
Ruby Red              3681.493417    92.428424   294.282078  4131.979631
Terra cotta           3493.297087   162.842780   606.873526  4047.521916
Turquoise              253.612143  1855.058958  2955.029449   624.954202
White                  412.341277  2400.807632  3095.612617   377.750811